# JVM Memory ko badha kar 4GB ya 3GB karein (Aapke PC mein RAM ke mutabiq)
org.gradle.jvmargs=-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Parallel builds enable karein
org.gradle.parallel=true

# Configuration cache enable kareین (Builds ko super fast banata hai)
org.gradle.configuration-cache=true

# File system watching enable karein taaki Gradle file changes turant detect kare
org.gradle.vfs.watch-fs=true

# Build cache enable karein
org.gradle.caching=true

android.useAndroidX=true
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
